version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: parcelpilot_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: parcelpilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d parcelpilot" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: parcelpilot_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/parcelpilot
      - SNAPSHOT_REF_TIME=2026-08-16 11:00:00+05:30
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app:/app/app
      - ./Data:/app/Data

  frontend:
    build: ./frontend
    container_name: parcelpilot_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
